Nombre = input("Cual es tu nombre? ")
Apellido = input("Cual es tu apellido? ")
Carrera = input("Cual es tu carrera? ")
Asignatura = input("Cual es esta asignatura? ")
Sede = input("En que sede estudias? ")
Año = input("En que año estamos? ")
Ciudad = input("En que ciudad estamos? ")
Edad = input("Que edad tienes? ")
print(" Tu nombre es " + Nombre + " " + Apellido + " estudias "+ Carrera +" esta es la asignatura de "+ Asignatura + " en la sede de INACAP " + Sede + ", este es el año " + Año + " nos encontramos en la ciudad de " + Ciudad + " y actualmente tienes " + Edad + " años." )